name: Marabou
ami: ami-0892d3c7ee96c0bf7
scripts_dir: vnncomp
manual_installation_step: True
run_installation_script_as_root: True
run_post_installation_script_as_root: False
run_toolkit_as_root: False
description: >
    Marabou is an SMT-based Neural Network Verification tool. It supports definition
    of logical combinations of linear constraints over any part of a neural network.
    It supports a wide range of types of activation functions and connections.
    